run:
  timeout: 90s
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude: ./errcheck_excludes.txt

  gofmt:
    simplify: true
  goimports:
    local-prefixes: gitlab.com/postgres-ai/database-lab
  dupl:
    threshold: 120
  goconst:
    min-len: 3
    min-occurrences: 5
  gomnd:
    settings:
      mnd:
        ignored-functions: strconv.Format*,os.*,strconv.Parse*,strings.SplitN,bytes.SplitN
  lll:
    line-length: 140
    tab-width: 1
  revive:
    min-confidence: 0.8
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 20
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  gocritic:
    disabled-checks:
      - regexpMust
      - rangeValCopy
      - appendAssign
      - hugeParam
    enabled-tags:
      - performance
  godot:
    scope: declarations

linters:
  enable:
    - deadcode
#    - depguard
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - goimports
    - gomnd
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - prealloc
    - revive
    - structcheck
    - stylecheck
    - unconvert
    - varcheck
    - unused
    - unparam
    - wsl
    - godot
  enable-all: false
  disable:
    - gosec
    - interfacer
    - gocyclo # currently unmaintained
    - depguard
  presets:
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - lll
        - errcheck
        - wsl
        - gomnd

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  new-from-rev: 33432c82a0a8d26108421b9be0a6aef4a8dbc1af
